### ISSUE TITLE
Exception when parsing "over 1 year ago" as Date

### ISSUE THREAD

**Issue by ricardokrieg** [tanordheim/json_mapper#1]
In this line:
https://github.com/tanordheim/json_mapper/blob/master/lib/json_mapper/attribute.rb#L43

This error occurs when using the freelancer-ruby gem.

``` ruby
Date.parse("over 1 year ago")
ArgumentError: invalid date
```

**Comment by tanordheim** [comment]
The gem doesn't support any other date formats than what the `Date.parse` method can handle, and date formats like that is not supported by that method.

I'll welcome a patch to fix that, if you're up for it, but otherwise I don't think that's a feature that needs to go in this gem. If you have a JSON data set that contains non-standard date formats like that, I think the best way to handle it would be to process the data before handing it to your JSON mapped model.
